apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - name: comment
        image: jaels/comment:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 9292
